server:
  port: 8086

spring:
  application:
    name: service-provider
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8081/eureka/

  instance:
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 2

mybatis:
  type-aliases-package: com.jk.model
  mapper-locations: classpath:mapping/mapper/*.xml
  config-locations: classpath:mapping/confg.xml


